name: test_calendar
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  json_annotation: ^4.8.1
  dio: ^5.4.1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  table_calendar: ^3.1.1
  intl: ^0.19.0
  pretty_dio_logger: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  riverpod_lint: ^2.3.10
  build_runner : ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  mockito: ^5.4.4


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: jetbrains
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
